MODEL_NAMES:
  vllm:
    name: vLLM（本地）
    url: https://docs.vllm.ai/
    base_url: http://host.docker.internal:50002/qwen3_32b_i4/v1
    default: Qwen/Qwen3-32B-AWQ
    env: VLLM_API_KEY
    models:
    - Qwen/Qwen3-32B-AWQ

EMBED_MODEL_INFO:
  vllm/qwen3_embedding:
    name: Qwen/Qwen3-Embedding-4B
    dimension: 1024
    base_url: http://host.docker.internal:50002/qwen3_embedding/v1/embeddings
    api_key: VLLM_API_KEY

RERANKER_LIST:
  vllm/bge_reranker_v2_m3:
    name: BAAI/bge-reranker-v2-m3
    base_url: http://host.docker.internal:50002/bge_reranker_v2_m3/v1/rerank
    api_key: VLLM_API_KEY